version: '3'
services:
  server:
    build:
      context: server
    volumes:
      - ./server/html:/var/www/html
    ports:
      - 8080:80
  mobile:
    build:
      context: mobile
    volumes:
      - ./mobile:/usr/src/app
      - ./shared_folder:/shared_folder
    environment:
      - NODE_ENV=development