version: '3'
services:
  server:
    container_name: area_server
    build:
      context: server
    volumes:
      - ./server/html:/var/www/html
    ports:
      - 8080:80
  mobile_user:
    container_name: area_mobile
    build:
      context: mobile
    volumes:
      - ./mobile:/usr/src/app
      - ./shared_folder:/shared_folder
    environment:
      - NODE_ENV=development
  client_web:
    container_name: area_web
    build:
      context: web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/code
      - ./shared_folder:/shared_folder
    ports:
      - "8081:8000"
    depends_on:
      - mobile_user
      - server