CREATE DATABASE area;
GRANT ALL PRIVILEGES ON area.* TO 'area'@'localhost' IDENTIFIED BY 'hello';

USE area;
CREATE TABLE users (
	id INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,

	PRIMARY KEY(id)
);

CREATE TABLE services (
	id INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
	name CHAR(255) NOT NULL,
	PRIMARY KEY(id),
	UNIQUE (name)
);

CREATE TABLE tokens (
	id INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
	user_id INT(8) UNSIGNED NOT NULL,
	service_id INT(8) UNSIGNED NOT NULL,
	token VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);