CREATE DATABASE area;
GRANT ALL PRIVILEGES ON area.* TO 'area'@'localhost' IDENTIFIED BY 'hello';

USE area;
CREATE TABLE users (
	id INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
	email CHAR(255) NOT NULL,
	username CHAR(255) NOT NULL,
	pwd CHAR(255) NOT NULL,
	imgur_access_token CHAR(255),
	imgur_refresh_token CHAR(255),
	enabled TINYINT(1) NOT NULL,
	PRIMARY KEY(id),
	UNIQUE(email),
	UNIQUE(username)
);

CREATE TABLE services (
	id INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
	name CHAR(255) NOT NULL,
	PRIMARY KEY(id),
	UNIQUE (name)
);

CREATE TABLE tokens (
	id INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
	user_id INT(8) UNSIGNED NOT NULL,
	service_id INT(8) UNSIGNED NOT NULL,
	token VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);